tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SFSENORTHAMERICA-LUKE_TURANSKI_SE_DEMO
      user: lturanski
      role: accountadmin
      database: TASTY_BYTES_DBT_DB
      schema: raw
      warehouse: COMPUTE_WH
      private_key_path: /Users/lturanski/.ssh/rsa_key.p8
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: True
      retry_all: False
      reuse_connections: True
